In [9]:
import pandas as pd
import ezodf
from modify_dfs import *
import os

In [2]:

s_fname = "C:\\Users\simmt\Code1\Pesticide\data\August_2022_rolling_reports.ods"
# doc = ezodf.opendoc(s_fname)

In [27]:
folder_path = 'C:\\Users\simmt\Code1\Pesticide\Pesticide-main\data_files'
file_path = []
for x in os.listdir(folder_path):
    file_path.append(os.path.join(folder_path,x) )

    
doc = ezodf.opendoc(file_path[0])
# get last sheet
sheet = doc.sheets[-4]

In [37]:
df_dict = {}
print(sheet.name)
for i, row in enumerate(sheet.rows()):
#     row is a list of cells
# #     assume the header is on the first row
    if i == 2:
    # columns as lists in a dictionary
        df_dict = {cell.value:[] for cell in row}
df_dict

TinTomatoes_BNA

{'1606/2016': [],
 '2016-04-15T00:00:00': [],
 'Sweet Harvest Peeled Plum Tomatoes': [],
 'Italy': [],
 'Aldi': [],
 'Newbridge Hill, Louth LN11 0NQ': [],
 'Aldi ': [],
 'Aldi Stores Ltd PO Box 26, Atherstone, Warwickshire CV9 2SH': [],
 'None were detected above the set RL': [],
 None: []}

In [48]:
data_sheet = []
for i,row in enumerate(sheet.rows()):
    if i==0:
        column_names = [cell.value for cell in row]
        print(column_names)
    else:
        data_sheet.append( [cell.value for cell in row] )
ddf = pd.DataFrame(data_sheet)

ddf.columns = column_names

ddf

['Sample ID', 'Date of Sampling', 'Description', 'Country of Origin', 'Retail Outlet', 'Address', 'Brand Name', 'Packer / Manufacturer', 'Pesticide residues found in mg/kg (MRL)', None]

,Sample ID,Date of Sampling,Description,Country of Origin,Retail Outlet,Address,Brand Name,Packer / Manufacturer,Pesticide residues found in mg/kg (MRL),None
0,1605/2016,2016-04-15T00:00:00,Sweet Harvest Chunky Chopped Tomatoes,Italy,Aldi,"Newbridge Hill, Louth LN11 0JT",Aldi,"Aldi Stores Ltd PO Box 26, Atherstone, Warwick...",None were detected above the set RL,None
1,1606/2016,2016-04-15T00:00:00,Sweet Harvest Peeled Plum Tomatoes,Italy,Aldi,"Newbridge Hill, Louth LN11 0NQ",Aldi,"Aldi Stores Ltd PO Box 26, Atherstone, Warwick...",None were detected above the set RL,None
2,1752/2016,2016-05-05T00:00:00,Chunky Chopped Tomatoes,Italy,Aldi,"Walsall Road, Cannock WS11 0EA",Aldi,"Aldi Stores Ltd PO Box 26, Atherstone, Warwick...",None were detected above the set RL,None
3,1753/2016,2016-05-05T00:00:00,Peeled Plum Tomatoes,Italy,Aldi,"Walsall Road, Cannock WS11 0EA",Aldi,"Aldi Stores Ltd PO Box 26, Atherstone, Warwick...",None were detected above the set RL,None
4,0400/2016,2016-05-10T00:00:00,Cherry Tomatoes,Italy,Asda,"Avon Road, Cannock WS11 1LH",Napolina,"Napolina Ltd Royal Liver Building, Pier Head, ...",None were detected above the set RL,None
5,1740/2016,2016-05-06T00:00:00,Smart Price Peeled Plum Tomatoes,Italy,Asda,"Avon Road, Cannock WS11 1LH",Asda,Asda Stores Ltd Leeds LS11 5AD,None were detected above the set RL,None
6,1622/2016 Organic,2016-04-16T00:00:00,Tarantella Organic Peeled Plum Tomatoes,Italy,Co-op,"Northgate, Louth LN11 0LT",Tarantella,"Community Foods Ltd Brent Terrace, London NW2 1LT",None were detected above the set RL,None
7,1638/2016,2016-04-16T00:00:00,Italian Chopped Tomatoes,Italy,Co-op,"Northgate, Louth LN11 0LT",Co-op,Co-operative Group Ltd Manchester M60 0AG,None were detected above the set RL,None
8,1607/2016,2016-04-15T00:00:00,Italian Plum Tomatoes,Italy,Morrisons,"150 Eastgate, Louth LN11 9AB",Morrisons,"Wm Morrison PLC Gain Lane, Bradford BD3 7DL",None were detected above the set RL,None
9,1608/2016,2016-04-15T00:00:00,Italian Chopped Tomatoes,Italy,Morrisons,"150 Eastgate, Louth LN11 9AB",Morrisons,"Wm Morrison PLC Gain Lane, Bradford BD3 7DL",None were detected above the set RL,None
10,1609/2016,2016-04-15T00:00:00,Tomato Fillets,Italy,Morrisons,"150 Eastgate, Louth LN11 9AB",Cirio,"Dawood Exports Ltd 5, Buroh Lane, 09-01, Singa...",None were detected above the set RL,None
11,1610/2016,2016-04-15T00:00:00,Peeled Plum Tomatoes,Italy,Morrisons,"150 Eastgate, Louth LN11 9AB",Cook Italian,"LDH La Doria Ltd Huntingdon, Cambridgeshire PE...",None were detected above the set RL,None
12,1611/2016,2016-04-15T00:00:00,Chopped Tomatoes,Italy,Morrisons,"150 Eastgate, Louth LN11 9AB",Napolina,"Napolina Ltd Royal Liver Building, Pier Head, ...",flonicamid (sum) 0.01 (MRL = 0.3),None
13,1612/2016,2016-04-15T00:00:00,Peeld Plum Tomatoes,Italy,Morrisons,"150 Eastgate, Louth LN11 9AB",Napolina,"Napolina Ltd Royal Liver Building, Pier Head, ...",None were detected above the set RL,None
14,1613/2016,2016-04-15T00:00:00,Chopped Tomatoes,Italy,Morrisons,"150 Eastgate, Louth LN11 9AB",Cook Italian,"LDH La Doria Ltd Parsons Green, St Ives, Cambr...",None were detected above the set RL,None
15,1614/2016,2016-04-15T00:00:00,Tuscan Chopped Tomatoes,Italy,Morrisons,"150 Eastgate, Louth LN11 9AB",Cirio,Conserve Italia Soc Co-op Agricola Via P Poggi...,None were detected above the set RL,None
16,1741/2016 Organic,2016-05-05T00:00:00,SO Organic Peeled Plum Tomatoes,Italy,Sainsburys,"Voyager Drive, Cannock WS11 8XD",Sainsburys,Sainsburys Supermarkets Ltd London EC1N 2HT,None were detected above the set RL,None
17,1742/2016,2016-05-05T00:00:00,Chopped Tomatoes,Italy,Sainsburys,"Voyager Drive, Cannock WS11 8XD",Napolina,"Napolina Ltd Royal Liver Building, Pier Head, ...",None were detected above the set RL,None
18,1743/2016 Organic,2016-05-05T00:00:00,SO Organic Chopped Tomatoes,Italy,Sainsburys,"Voyager Drive, Cannock WS11 8XD",Sainsburys,Sainsburys Supermarkets Ltd London EC1N 2HT,None were detected above the set RL,None
19,1744/2016,2016-05-05T00:00:00,Peeled Plum Tomatoes,Italy,Sainsburys,"Voyager Drive, Cannock WS11 8XD",Napolina,"Napolina Ltd Royal Liver Building, Pier Head, ...",None were detected above the set RL,None
20,1745/2016,2016-05-05T00:00:00,Plum Tomatoes,Italy,Sainsburys,"Voyager Drive, Cannock WS11 8XD",Sainsburys,Sainsburys Supermarkets Ltd London EC1N 2HT,None were detected above the set RL,None
21,1747/2016,2016-05-05T00:00:00,Chopped Tomatoes,Italy,Sainsburys,"Voyager Drive, Cannock WS11 8XD",Cirio,Conserve Italia Soc Co-op Agricola Via P Poggi...,None were detected above the set RL,None
22,1748/2016,2016-05-05T00:00:00,Chopped Tomatoes,Italy,Sainsburys,"Voyager Drive, Cannock WS11 8XD",Cook Italian,"LDH La Doria Ltd Parsons Green, St Ives, Cambr...",None were detected above the set RL,None
23,1751/2016,2016-05-05T00:00:00,Chopped Tomatoes,Italy,Tesco,"Heath Way, Cannock WS12 3YY",Tesco,Tesco Stores Ltd Cheshunt EN8 9SL,None were detected above the set RL,None
24,None,None,None,None,None,None,None,None,None,None

In [4]:
def import_ods(fname):
    doc = ezodf.opendoc(s_fname)
    for i, sheet in enumerate(doc.sheets):
        if i!=0: #ignore 1st sheet
            product = sheet.name
            print(product)
            
            df_new =import_ods_inner(sheet)
            df_new.columns = df_new.columns.str.strip()
            try:
                df = pd.concat([df,df_new])
            except:
                df = df_new
                
    return df
            
def import_ods_inner(sheet):
    df_dict = {}
    for i, row in enumerate(sheet.rows()):
    #     row is a list of cells
# #     assume the header is on the first row
        if i == 1:
        # columns as lists in a dictionary
            df_dict = {cell.value:[] for cell in row}

    # create index for the column headers
    for i,row in enumerate(sheet.rows()):
        if i == 0:
            continue
        elif i == 1:
            col_index = [cell.value for cell in row]
            continue
        for j,cell in enumerate(row):
            df_dict[col_index[j]].append(cell.value)
            
    # delete none column
    try:
        del df_dict[None]
    except:
        pass
    # and convert to a DataFrame
    df = pd.DataFrame(df_dict)
    
    # fill based on previous values    
    df.fillna(method='ffill', inplace=True)

    return df

In [7]:
df = import_ods(s_fname)

modify_df(df)
# import re
# def extract_pcode(x):  
#     regexp = r'([A-Za-z]+[0-9]+\s[0-9]+[A-Za-z]+$)'
#     try:
#         return re.findall(regexp,x)[0]
#     except:
#         return 0
# eg_pc = 'hdwhck ss1 2wg'
# regexp = r'([A-Za-z]+[0-9]+\s[0-9]+[A-Za-z]+$)'
                      
                      
# # df = extract_pcode(df,'Address')
# df['Address'].apply(extract_pcode)

Beans_with_Pods_(GB)
Grapes_(GB)
Potatoes_(GB)

,sample_id,date_of_sampling,description,country_of_origin,sampling_point,address,brand_name,packer_/_manufacturer_/_importer,pesticide_residues_found_in_mg/kg_(mrl),address_postcode,packer__postcode,chem_name,amount_detected,mrl
0,3729/2022,2022-08-08T00:00:00,Extra Fine Beans,Guatemala,Tesco,"19-20 Boundary Road, Brighton, Portslade BN41 1GB",Tesco,"Tesco Stores Ltd Tesco House, Shire Park, Kest...",tebuconazole 0.03 (MRL = 2),BN41 1GB,AL7 1GA,tebuconazole,0.03,2
1,3729/2022,2022-08-08T00:00:00,Extra Fine Beans,Guatemala,Tesco,"19-20 Boundary Road, Brighton, Portslade BN41 1GB",Tesco,"Tesco Stores Ltd Tesco House, Shire Park, Kest...",fluopyram 0.06 (MRL = 1),BN41 1GB,AL7 1GA,fluopyram,0.06,1
2,5951/2022,2022-08-08T00:00:00,Extra Fine Green Beans,Kenya,Aldi,"9-10 Boulevard Retail Park, Aberdeen AB11 5EJ",Specially Selected,"Aldi Stores Ltd PO Box 26. Atherstone, Warwick...",cyantraniliprole 0.02 (MRL = 1.5),AB11 5EJ,CV9 2SH,cyantraniliprole,0.02,1.5
3,1941/2022,2022-08-08T00:00:00,Green Beans,UK,Asda,"Jockey Lane, Monks Cross Drive, Huntington, Yo...",Asda,"ASDA Stores Ltd Great Wilson Street, Leeds LS1...",n/a,YO32 9LF,LS11 5AD,0,0,0
4,1975/2022,2022-08-08T00:00:00,Green Beans,UK,Marks & Spencer,"George Lane, South Woodford E18 1AY",Marks & Spencer,Marks & Spencer Plc PO Box 3339. Chester CH99 9QS,flonicamid (sum) 0.1 (MRL = 1.5),E18 1AY,CH99 9QS,flonicamid (sum),0.1,1.5
5,1901/2022,2022-08-08T00:00:00,Trimmed Beans,Kenya,Morrisons,"Sutton Road, Maidstone ME15 9NN",Morrisons,"Wm Morrison Supermarkets Plc 71 Gain Lane, Bra...",azoxystrobin 0.02 (MRL = 3),ME15 9NN,BD3 7DL,azoxystrobin,0.02,3
6,1946/2022,2022-08-08T00:00:00,Runner Beans,UK,Sainsburys,30 Mere Green Road B75 5BT,Sainsburys,"Sainsburys Supermarkets Ltd 33 Holborn, London...",n/a,B75 5BT,0,0,0,0
7,1946/2022,2022-08-08T00:00:00,Runner Beans,UK,Sainsburys,30 Mere Green Road B75 5BT,Sainsburys,"Sainsburys Supermarkets Ltd 33 Holborn, London...",n/a,B75 5BT,0,0,0,0
8,2003/2022,2022-08-08T00:00:00,Ralli Wonky Red Grapes,Spain,Aldi,"9-10 Boulevard Retail Park, Aberdeen AB11 5EJ",Everyday Essentials,"Aldi Stores Ltd PO Box 26. Atherstone, Warwick...",spirotetramat (sum) 0.05 (MRL = 2),AB11 5EJ,CV9 2SH,spirotetramat (sum),0.05,2
9,2003/2022,2022-08-08T00:00:00,Ralli Wonky Red Grapes,Spain,Aldi,"9-10 Boulevard Retail Park, Aberdeen AB11 5EJ",Everyday Essentials,"Aldi Stores Ltd PO Box 26. Atherstone, Warwick...",trifloxystrobin 0.1 (MRL = 3),AB11 5EJ,CV9 2SH,trifloxystrobin,0.1,3
10,6126/2022,2022-08-09T00:00:00,ARRA 15 Seedless White Grapes,Morocco,Aldi,"Faverdale North, Faverdale Industrial Estate, ...",Nature's Pick,Elite Harvest Maroc Morocco,azoxystrobin 0.02 (MRL = 3),DL3 0UW,0,azoxystrobin,0.02,3
11,1253/2022,2022-08-10T00:00:00,Tawny Seedless Red Grapes,Spain,Asda,"Erith CDC, Isis Reach, Norman Road, Belvedere ...",Asda,IPL Ltd ME9 7TT,metalaxyl (sum) 0.02 (MRL = 2),DA17 6JY,ME9 7TT,metalaxyl (sum),0.02,2
12,1253/2022,2022-08-10T00:00:00,Tawny Seedless Red Grapes,Spain,Asda,"Erith CDC, Isis Reach, Norman Road, Belvedere ...",Asda,IPL Ltd ME9 7TT,boscalid 0.03 (MRL = 5),DA17 6JY,ME9 7TT,boscalid,0.03,5
13,1253/2022,2022-08-10T00:00:00,Tawny Seedless Red Grapes,Spain,Asda,"Erith CDC, Isis Reach, Norman Road, Belvedere ...",Asda,IPL Ltd ME9 7TT,ethephon 0.8 (MRL = 1),DA17 6JY,ME9 7TT,ethephon,0.8,1
14,1253/2022,2022-08-10T00:00:00,Tawny Seedless Red Grapes,Spain,Asda,"Erith CDC, Isis Reach, Norman Road, Belvedere ...",Asda,IPL Ltd ME9 7TT,fluopyram 0.2 (MRL = 1.5),DA17 6JY,ME9 7TT,fluopyram,0.2,1.5
15,1258/2022,2022-08-10T00:00:00,Superior Seedless Green Grapes,Italy,Asda,"Erith CDC, Isis Reach, Norman Road, Belvedere ...",Asda,IPL Ltd ME9 7TT,spiroxamine 0.03 (MRL = 0.6),DA17 6JY,ME9 7TT,spiroxamine,0.03,0.6
16,1258/2022,2022-08-10T00:00:00,Superior Seedless Green Grapes,Italy,Asda,"Erith CDC, Isis Reach, Norman Road, Belvedere ...",Asda,IPL Ltd ME9 7TT,acetamiprid 0.01 (MRL = 0.5),DA17 6JY,ME9 7TT,acetamiprid,0.01,0.5
17,1951/2022,2022-08-08T00:00:00,Seedless Red Grapes,Egypt,Asda,"Jockey Lane, Monks Cross Drive, Huntington, Yo...",Asda,"ASDA Stores Ltd Great Wilson Street, Leeds LS1...",cyprodinil 0.03 (MRL = 3),YO32 9LF,LS11 5AD,cyprodinil,0.03,3
18,1951/2022,2022-08-08T00:00:00,Seedless Red Grapes,Egypt,Asda,"Jockey Lane, Monks Cross Drive, Huntington, Yo...",Asda,"ASDA Stores Ltd Great Wilson Street, Leeds LS1...",azoxystrobin 0.03 (MRL = 3),YO32 9LF,LS11 5AD,azoxystrobin,0.03,3
19,1951/2022,2022-08-08T00:00:00,Seedless Red Grapes,Egypt,Asda,"Jockey Lane, Monks Cross Drive, Huntington, Yo...",Asda,"ASDA Stores Ltd Great Wilson Street, Leeds LS1...",ethephon 0.08 (MRL = 1),YO32 9LF,LS11 5AD,ethephon,0.08,1
20,6155/2022,2022-08-22T00:00:00,Premium Thompson Seedless Grapes,Greece,George Perry Ltd,"Birmingham Wholesale Market, Noble Way B6 7EU",None stated,Koufozisis SA Cretan Root Ano Archanes. Herakl...,spirotetramat (sum) 0.01 (MRL = 2),B6 7EU,0,spirotetramat (sum),0.01,2
21,6155/2022,2022-08-22T00:00:00,Premium Thompson Seedless Grapes,Greece,George Perry Ltd,"Birmingham Wholesale Market, Noble Way B6 7EU",None stated,Koufozisis SA Cretan Root Ano Archanes. Herakl...,chlorantraniliprole 0.1 (MRL = 1),B6 7EU,0,chlorantraniliprole,0.1,1
22,6155/2022,2022-08-22T00:00:00,Premium Thompson Seedless Grapes,Greece,George Perry Ltd,"Birmingham Wholesale Market, Noble Way B6 7EU",None stated,Koufozisis SA Cretan Root Ano Archanes. Herakl...,etofenprox 0.02 (MRL = 4*),B6 7EU,0,0,0,0
23,1227/2022 Organic,2022-08-23T00:00:00,ARRA 30 Grapes,Italy,Langridge Organic Products Ltd,"Unit 6 Felthambrook Industrial Estate, Feltham...",None stated,O.P. Orlofrutticola Jonica C. delama di Pozzo ...,n/a,TW13 7DU,0,0,0,0
24,3731/2022,2022-08-08T00:00:00,Ralli Red Seedless Grapes,Spain,Lidl,"Goldstone Retail Park, Newton Road, Hove BN3 7PN",Oaklands,"Lidl GT. Britain Ltd Lidl House, 14 Kingston R...",boscalid 0.4 (MRL = 5),BN3 7PN,KT5 9NU,boscalid,0.4,5
25,3731/2022,2022-08-08T00:00:00,Ralli Red Seedless Grapes,Spain,Lidl,"Goldstone Retail Park, Newton Road, Hove BN3 7PN",Oaklands,"Lidl GT. Britain Ltd Lidl House, 14 Kingston R...",spirotetramat (sum) 0.05 (MRL = 2),BN3 7PN,KT5 9NU,spirotetramat (sum),0.05,2
26,3731/2022,2022-08-08T00:00:00,Ralli Red Seedless Grapes,Spain,Lidl,"Goldstone Retail Park, Newton Road, Hove BN3 7PN",Oaklands,"Lidl GT. Britain Ltd Lidl House, 14 Kingston R...",trifloxystrobin 0.07 (MRL = 3),BN3 7PN,KT5 9NU,trifloxystrobin,0.07,3
27,0656/2022,2022-08-08T00:00:00,Sweet Celebration Seedless Red Grapes,Spain,Morrisons,"Produce Depot, Bristol Road, Bridgwater TA6 4AT",Morrisons,Cutler Bradford BD4 9LR,deltamethrin 0.03 (MRL = 0.2),TA6 4AT,BD4 9LR,deltamethrin,0.03,0.2
28,0656/2022,2022-08-08T00:00:00,Sweet Celebration Seedless Red Grapes,Spain,Morrisons,"Produce Depot, Bristol Road, Bridgwater TA6 4AT",Morrisons,Cutler Bradford BD4 9LR,cyprodinil 0.02 (MRL = 3),TA6 4AT,BD4 9LR,cyprodinil,0.02,3
29,0656/2022,2022-08-08T00:00:00,Sweet Celebration Seedless Red Grapes,Spain,Morrisons,"Produce Depot, Bristol Road, Bridgwater TA6 4AT",Morrisons,Cutler Bradford BD4 9LR,spirotetramat (sum) 0.07 (MRL = 2),TA6 4AT,BD4 9LR,spirotetramat (sum),0.07,2
30,0656/2022,2022-08-08T00:00:00,Sweet Celebration Seedless Red Grapes,Spain,Morrisons,"Produce Depot, Bristol Road, Bridgwater TA6 4AT",Morrisons,Cutler Bradford BD4 9LR,fluopyram 0.04 (MRL = 1.5),TA6 4AT,BD4 9LR,fluopyram,0.04,1.5
31,0656/2022,2022-08-08T00:00:00,Sweet Celebration Seedless Red Grapes,Spain,Morrisons,"Produce Depot, Bristol Road, Bridgwater TA6 4AT",Morrisons,Cutler Bradford BD4 9LR,ethephon 0.4 (MRL = 1),TA6 4AT,BD4 9LR,ethephon,0.4,1
32,1903/2022,2022-08-08T00:00:00,Sweet Celebration Seedless Red Grapes,Spain,Morrisons,"Sutton Road, Maidstone ME15 9NN",Morrisons,"Wm Morrison Supermarkets Plc 71 Gain Lane, Bra...",metalaxyl (sum) 0.02 (MRL = 2),ME15 9NN,BD3 7DL,metalaxyl (sum),0.02,2
33,1903/2022,2022-08-08T00:00:00,Sweet Celebration Seedless Red Grapes,Spain,Morrisons,"Sutton Road, Maidstone ME15 9NN",Morrisons,"Wm Morrison Supermarkets Plc 71 Gain Lane, Bra...",fluopyram 0.02 (MRL = 1.5),ME15 9NN,BD3 7DL,fluopyram,0.02,1.5
34,1262/2022,2022-08-16T00:00:00,Midnight Beauty Black Grapes,Egypt,Reynolds Catering Supplies Ltd,"National Distribution Centre, Britannia Road E...",None stated,Pico Modern Agriculture Co. Shagaret Eldor Str...,trifloxystrobin 0.01 (MRL = 3),EN8 7RQ,0,trifloxystrobin,0.01,3
35,1262/2022,2022-08-16T00:00:00,Midnight Beauty Black Grapes,Egypt,Reynolds Catering Supplies Ltd,"National Distribution Centre, Britannia Road E...",None stated,Pico Modern Agriculture Co. Shagaret Eldor Str...,ethephon 0.08 (MRL = 1),EN8 7RQ,0,ethephon,0.08,1
36,1262/2022,2022-08-16T00:00:00,Midnight Beauty Black Grapes,Egypt,Reynolds Catering Supplies Ltd,"National Distribution Centre, Britannia Road E...",None stated,Pico Modern Agriculture Co. Shagaret Eldor Str...,fenhexamid 0.08 (MRL = 15),EN8 7RQ,0,fenhexamid,0.08,15
37,1947/2022,2022-08-08T00:00:00,Superior White Seedless Grapes,Italy,Sainsburys,30 Meregreen Road B75 5BT,Sainsburys,"Sainsburys Supermarkets Ltd 33 Holborn, London...",spiroxamine 0.2 (MRL = 0.6),B75 5BT,0,spiroxamine,0.2,0.6
38,1947/2022,2022-08-08T00:00:00,Superior White Seedless Grapes,Italy,Sainsburys,30 Meregreen Road B75 5BT,Sainsburys,"Sainsburys Supermarkets Ltd 33 Holborn, London...",metrafenone 0.2 (MRL = 7),B75 5BT,0,metrafenone,0.2,7
39,1947/2022,2022-08-08T00:00:00,Superior White Seedless Grapes,Italy,Sainsburys,30 Meregreen Road B75 5BT,Sainsburys,"Sainsburys Supermarkets Ltd 33 Holborn, London...",metrafenone 0.2 (MRL = 7),B75 5BT,0,metrafenone,0.2,7
40,1281/2022,2022-07-27T00:00:00,Lady Rosetta Ware Potatoes,UK,Kolak Snack Foods,"308-310 Elveden Road, London NW10 7ST",None stated,"Mercian Ltd Unit 3 & 4, The Barns, Highfield F...",n/a,NW10 7ST,0,0,0,0
41,1282/2022,2022-07-27T00:00:00,Lady Rosetta Ware Potatoes,UK,Kolak Snack Foods,"308-310 Elveden Road, London NW10 7ST",None stated,"Mercian Ltd Unit 3 & 4, The Barns, Highfield F...",n/a,NW10 7ST,0,0,0,0
42,1072/2022,2022-08-02T00:00:00,Markies Ware Potatoes,UK,Linwood Crops Ltd,"Linwood Farm, March PE15 0YG",None stated,"PJ Lee and Sons Ltd High Flyer Farm, Ely CB7 4RA",maleic hydrazide 18 (MRL = 60),PE15 0YG,CB7 4RA,maleic hydrazide,18,60
43,0810/2022,2022-07-27T00:00:00,Maris Piper Ware Potatoes,Israel,London Gateway Port Ltd,"Stanford-Le-Hope, Essex SS17 9DY",None stated,"Yapro Ltd Hanegev Building, Reem Junction DN S...",n/a,SS17 9DY,0,0,0,0
44,0813/2022 Organic,2022-07-27T00:00:00,Organic Valor Ware Potatoes,Israel,London Gateway Port Ltd,"Stanford-Le-Hope, Essex SS17 9DY",None stated,Alumim Atzmona Potatoes Ltd Mivtachim DN Negev...,n/a,SS17 9DY,0,0,0,0
45,0814/2022,2022-07-27T00:00:00,Soraya Ware Potatoes,Israel,London Gateway Port Ltd,"Stanford-Le-Hope, Essex SS17 9DY",None stated,"Yapro Ltd Hanegev Building, Reem Junction DN S...",n/a,SS17 9DY,0,0,0,0
46,0815/2022,2022-07-27T00:00:00,Maris Piper Ware Potatoes,Israel,London Gateway Port Ltd,"Stanford-Le-Hope, Essex SS17 9DY",None stated,"Atzmona Mivtachim DN Negev, 85440, Israel",n/a,SS17 9DY,0,0,0,0
47,0876/2022,2022-08-25T00:00:00,Accord Ware Potatoes,UK,PG Chips 2000 Ltd,"Elton Fold Mill, Harvey Street, Bury, Greater ...",None stated,"JT Hopkins & Sons Carsaig Farm, High Street, W...",n/a,BL8 1FZ,ON9 2BT,0,0,0
48,0873/2022,2022-07-26T00:00:00,Lady Rosetta Ware Potatoes,UK,Walkers Snack Foods Ltd,"Pennine Place, Pimbo, Skelmersdale WN8 9QF",None stated,"Mercian Ltd Unit 3 & 4, The Barns, Highfield F...",n/a,WN8 9QF,SK11 9BN,0,0,0
49,0919/2022,2022-07-26T00:00:00,Lady Rosetta Ware Potatoes,UK,Walkers Snack Foods Ltd,"Pennine Place, Pimbo, Skelmersdale WN8 9QF",None stated,R.S. Cockerill (York) Ltd Providence Business ...,n/a,WN8 9QF,YO19 5AE,0,0,0
50,0919/2022,2022-07-26T00:00:00,Lady Rosetta Ware Potatoes,UK,Walkers Snack Foods Ltd,"Pennine Place, Pimbo, Skelmersdale WN8 9QF",None stated,R.S. Cockerill (York) Ltd Providence Business ...,n/a,WN8 9QF,YO19 5AE,0,0,0

In [98]:
# convert the first sheet to a pandas.DataFrame
sheet = doc.sheets[2]
product = sheet.name
df_dict = {}
for i, row in enumerate(sheet.rows()):
#     row is a list of cells
# #     assume the header is on the first row
    if i == 1:
        # columns as lists in a dictionary
#         print(cell.value)
#         df_dict.update({cell.value:[]})
        df_dict = {cell.value:[] for cell in row}
# df_dict

#         # create index for the column headers
for i,row in enumerate(sheet.rows()):
    if i == 0:
        continue
    elif i == 1:
        col_index = [cell.value for cell in row]
#         print([cell.value for cell in row])
        continue
    for j,cell in enumerate(row):
#         print (j,cell.value)
        df_dict[col_index[j]].append(cell.value)
# # # and convert to a DataFrame
try:
    del df_dict[None]
except:
    pass

df = pd.DataFrame(df_dict)


df.head()

,Sample ID,Date of Sampling,Description,Country of Origin,Sampling Point,Address,Brand Name,Packer / Manufacturer / Importer,Pesticide residues found in mg/kg (MRL)
0,2493/2022,2022-09-05T00:00:00,Ivory White Grapes,Spain,Aldi,"Cameron Toll Shopping Centre, 6 Lady Road, Edi...",Everyday Essentials,"Aldi Stores Ltd PO Box 26. Atherstone, Warwick...",deltamethrin 0.02 (MRL = 0.2)
1,2493/2022,2022-09-05T00:00:00,Ivory White Grapes,Spain,Aldi,"Cameron Toll Shopping Centre, 6 Lady Road, Edi...",Everyday Essentials,"Aldi Stores Ltd PO Box 26. Atherstone, Warwick...",cyazofamid 0.02 (MRL = 2)
2,2493/2022,2022-09-05T00:00:00,Ivory White Grapes,Spain,Aldi,"Cameron Toll Shopping Centre, 6 Lady Road, Edi...",Everyday Essentials,"Aldi Stores Ltd PO Box 26. Atherstone, Warwick...",trifloxystrobin 0.03 (MRL = 3)
3,2493/2022,2022-09-05T00:00:00,Ivory White Grapes,Spain,Aldi,"Cameron Toll Shopping Centre, 6 Lady Road, Edi...",Everyday Essentials,"Aldi Stores Ltd PO Box 26. Atherstone, Warwick...",spirotetramat (sum) 0.02 (MRL = 2)
4,2493/2022,2022-09-05T00:00:00,Ivory White Grapes,Spain,Aldi,"Cameron Toll Shopping Centre, 6 Lady Road, Edi...",Everyday Essentials,"Aldi Stores Ltd PO Box 26. Atherstone, Warwick...",fluopyram 0.6 (MRL = 1.5)

In [90]:
[ (x, len(df_dict[x])) for x in df_dict]
#

[('Sample ID', 34),
 ('Date of Sampling', 34),
 ('Description', 34),
 ('Country of Origin', 34),
 ('Sampling Point', 34),
 ('Address', 34),
 ('Brand Name', 34),
 ('Packer / Manufacturer / Importer', 34),
 ('Pesticide residues found in mg/kg (MRL)', 34)]

In [58]:
del df[None]
df.head()

,Sample ID,Date of Sampling,Description,Country of Origin,Sampling Point,Address,Brand Name,Packer / Manufacturer / Importer,Pesticide residues found in mg/kg (MRL)
0,0753/2022,2022-09-15T00:00:00,Rooster Ware Potatoes,UK,Albert Bartlett Potatoes Ltd,"Kirton Holme, Kirton. Boston PE20 1TT",None stated,,None were detected above the set RL
1,0941/2022,2022-08-24T00:00:00,Sagitta Potatoes,UK,ARG Garrett,New College Farm PE33 9AZ,None stated,Bradmount Foods 14 Dessert Martin Road BT45 7RB,None were detected above the set RL
2,0940/2022,2022-09-07T00:00:00,Lanomma Potatoes,UK,Burgess Farm Produce,"East Bank Sutton Bridge, Spalding PE12 9YB",None stated,Robert Davies Wisbech,None were detected above the set RL
3,1077/2022,2022-09-12T00:00:00,Challenger Ware Potatoes,UK,Lamb Weston Meijer,"Weasenham Lane, Wisbech PE13 2RN",None stated,Scott Newman,fluopyram 0.01 (MRL = 0.15)
4,0793/2022,2022-09-06T00:00:00,Marfona Unwashed Potatoes,UK,Mack Wholesale,"40 Oriana Way, Southhampton SO16 0YU",None stated,"PK Farms Willowdene Farm, Armstrong Lane, Bost...",None were detected above the set RL

In [45]:
df.describe()

,Sample ID,Date of Sampling,Description,Country of Origin,Sampling Point,Address,Brand Name,Packer / Manufacturer / Importer,Pesticide residues found in mg/kg (MRL)
count,10,10,10,10,10,10,10,10,10
unique,10,9,8,2,10,10,1,10,4
top,0940/2022,2022-08-31T00:00:00,Sagitta Potatoes,UK,Mack Wholesale,"40 Oriana Way, Southhampton SO16 0YU",None stated,KP Crisps,None were detected above the set RL
freq,1,2,2,9,1,1,10,1,6

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 10 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Sample ID                                10 non-null     object
 1   Date of Sampling                         10 non-null     object
 2   Description                              10 non-null     object
 3   Country of Origin                        10 non-null     object
 4   Sampling Point                           10 non-null     object
 5   Address                                  10 non-null     object
 6   Brand Name                               10 non-null     object
 7   Packer / Manufacturer / Importer         10 non-null     object
 8   Pesticide residues found in mg/kg (MRL)  10 non-null     object
 9   None                                     0 non-null      object
dtypes: object(10)
memory usage: 1008.0+ bytes

In [57]:
list(df)

['Sample ID',
 'Date of Sampling',
 'Description',
 'Country of Origin',
 'Sampling Point',
 'Address',
 'Brand Name',
 'Packer / Manufacturer / Importer',
 'Pesticide residues found in mg/kg (MRL)',
 None]

In [59]:
def modify_df(df):
    
    # remove null column at end
    del df[None]
    # fill na values
    df.fillna(method='ffill', inplace=True)
    
     
def extract_pcode(df,col):  
    regexp = r'([A-Za-z]*[0-9]*\s[0-9]*[A-Za-z]*$)'
    
    df[col+'_post_code']=df[col].str.extract(regexp)
    return df
    
def extract_pesticide(df):
    
    df.replace({'None were detected above the set RL': 'n/a'}, regex=True, inplace=True)
    
    df2=df['pesticide_residues_found_in_mg/kg_(mrl)'].str.extract(r'(.*)\s(\d[\d.]*)\s+\(MRL\s*=\s*(\d[\d.]*)\)')

    df2.fillna(0, inplace=True)
    
    df2.rename(columns={0:'chem_name',1:'amount_detected',2:'mrl'},inplace=True)
   
    
    return df2
    
    
def rename_cols(df):
    renaming_dict = {
    old_name : new_name 
        for old_name,new_name 
        in zip(list(df),[new_name.lower().replace(' ','_') 
                         for new_name in list(df)])
    }

    df = df.rename(columns=renaming_dict)
    return df

Index(['Sample ID', 'Date of Sampling', 'Description', 'Country of Origin',
       'Sampling Point', 'Address', 'Brand Name',
       'Packer / Manufacturer / Importer',
       'Pesticide residues found in mg/kg (MRL)'],
      dtype='object')

In [47]:
# # df['Address'][0].str.extract(r')
# test_add = df['Address'][0]
# print(test_add)
# import re

# regexp = r'([A-Za-z]*[0-9]*\s[0-9]*[A-Za-z]*$)'
# re.search(regexp, test_add)

# print(df.Address.head(10))

# dfpcode=df.Address.str.extract(regexp)

# len(df), len(dfpcode)

In [34]:
# 

# df2

,level_0,index,Sample ID,Date of Sampling,Description,Country of Origin,Sampling Point,Address,Brand Name,Packer / Manufacturer / Importer,Pesticide residues found in mg/kg (MRL),chem_name,amount_detected,mrl
0,0,0,Dwarf Beans,None,None,None,None,None,None,None,None,0,0,0
1,1,1,2704/2022,20/09/2022,Dwarf Beans,UK,WM Morrison Supermarkets PLC,"Dorcan House Site, Eldene Drive, Swindon SN3 3TX",Morrisons,"Wm Morrisons Supermarkets PLC 71 Gain Lane, Br...",None were detected above the set RL,0,0,0
2,2,2,Fine Beans,20/09/2022,Dwarf Beans,UK,WM Morrison Supermarkets PLC,"Dorcan House Site, Eldene Drive, Swindon SN3 3TX",Morrisons,"Wm Morrisons Supermarkets PLC 71 Gain Lane, Br...",None were detected above the set RL,0,0,0
3,3,3,2045/2022,20/09/2022,Trimmed Fine Beans,Kenya,Asda,"Highweek Street, Newton Abbot TQ12 1TG",Asda,"ASDA Stores Ltd Great Wilson Street, Leeds LS1...",None were detected above the set RL,0,0,0
4,4,4,2701/2022,20/09/2022,Extra Fine Beans,Kenya,Tesco,"Askham Bar, Tadcaster Road, York YO24 1LW",Tesco Finest,"Tesco Stores Ltd Tesco House, Shire Park, Kest...",cyantraniliprole 0.04 (MRL = 1.5),cyantraniliprole,0.04,1.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,68,6,0792/2022,2022-09-08T00:00:00,Marfona Unwashed Potatoes,UK,Stoke Fruit Farm,"77 Havant Road, Hayling Island, Hampshire PO11...",None stated,"Stoke Fruit Farm 77 Havant Road, Hayling Islan...",maleic hydrazide 7.7 (MRL = 60),maleic hydrazide,7.7,60
69,69,7,0765/2022,2022-09-14T00:00:00,Sagitta Potatoes,UK,Total Produce Ltd.,"Callywith Gate Industrial Estate, Launceston R...",None stated,"CS Duston & Son Colwith Farm, Par, Cornwall",maleic hydrazide 17 (MRL = 60),maleic hydrazide,17,60
70,70,8,0938/2022,2022-09-01T00:00:00,Marfona Ware Potatoes,UK,Tulipland Potatoes Ltd,"Fengate, Moulton Chapel PE12 0XL",None stated,Garden of Elveden,None were detected above the set RL,0,0,0
71,71,9,0833/2022,2022-08-31T00:00:00,Lady Rosetta,England (UK),Tyrrells Crisps,"Tyrrells Court, Stretford Bridge, Leominster H...",None stated,KP Crisps,None were detected above the set RL,0,0,0
72,72,10,0833/2022,2022-08-31T00:00:00,Lady Rosetta,England (UK),Tyrrells Crisps,"Tyrrells Court, Stretford Bridge, Leominster H...",None stated,KP Crisps,None were detected above the set RL,0,0,0

In [32]:
from modify_dfs import *

df2 = rename_cols(df)
df2 = extract_pesticide(df2)
df2

           chem_name amount_detected  mrl
0                  0               0    0
1                  0               0    0
2                  0               0    0
3                  0               0    0
4   cyantraniliprole            0.04  1.5
..               ...             ...  ...
68  maleic hydrazide             7.7   60
69  maleic hydrazide              17   60
70                 0               0    0
71                 0               0    0
72                 0               0    0

[73 rows x 3 columns]

In [62]:
df2 = extract_pcode(df,'Address')
df2.head()

,Sample ID,Date of Sampling,Description,Country of Origin,Sampling Point,Address,Brand Name,Packer / Manufacturer / Importer,Pesticide residues found in mg/kg (MRL),Address_post_code
0,0753/2022,2022-09-15T00:00:00,Rooster Ware Potatoes,UK,Albert Bartlett Potatoes Ltd,"Kirton Holme, Kirton. Boston PE20 1TT",None stated,,None were detected above the set RL,PE20 1TT
1,0941/2022,2022-08-24T00:00:00,Sagitta Potatoes,UK,ARG Garrett,New College Farm PE33 9AZ,None stated,Bradmount Foods 14 Dessert Martin Road BT45 7RB,None were detected above the set RL,PE33 9AZ
2,0940/2022,2022-09-07T00:00:00,Lanomma Potatoes,UK,Burgess Farm Produce,"East Bank Sutton Bridge, Spalding PE12 9YB",None stated,Robert Davies Wisbech,None were detected above the set RL,PE12 9YB
3,1077/2022,2022-09-12T00:00:00,Challenger Ware Potatoes,UK,Lamb Weston Meijer,"Weasenham Lane, Wisbech PE13 2RN",None stated,Scott Newman,fluopyram 0.01 (MRL = 0.15),PE13 2RN
4,0793/2022,2022-09-06T00:00:00,Marfona Unwashed Potatoes,UK,Mack Wholesale,"40 Oriana Way, Southhampton SO16 0YU",None stated,"PK Farms Willowdene Farm, Armstrong Lane, Bost...",None were detected above the set RL,SO16 0YU